/* 
 * The OGC API - Processes
 *
 * WARNING - THIS IS WORK IN PROGRESS
 *
 * OpenAPI spec version: 1.0-draft.5
 * Contact: b.pross@52north.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AllOfdescriptionTypeAdditionalParameters
    /// </summary>
    [DataContract]
    public partial class AllOfdescriptionTypeAdditionalParameters : Metadata, IEquatable<AllOfdescriptionTypeAdditionalParameters>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AllOfdescriptionTypeAdditionalParameters" /> class.
        /// </summary>
        /// <param name="parameters">parameters.</param>
        public AllOfdescriptionTypeAdditionalParameters(List<AdditionalParameter> parameters,
                                                        string title,
                                                        string role,
                                                        string href) : base()
        {
            this.Parameters = parameters;
        }

        /// <summary>
        /// Gets or Sets Parameters
        /// </summary>
        [DataMember(Name = "parameters", EmitDefaultValue = false)]
        public List<AdditionalParameter> Parameters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AllOfdescriptionTypeAdditionalParameters {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AllOfdescriptionTypeAdditionalParameters);
        }

        /// <summary>
        /// Returns true if AllOfdescriptionTypeAdditionalParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of AllOfdescriptionTypeAdditionalParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AllOfdescriptionTypeAdditionalParameters input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                (
                    this.Parameters == input.Parameters ||
                    this.Parameters != null &&
                    input.Parameters != null &&
                    this.Parameters.SequenceEqual(input.Parameters)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Parameters != null)
                    hashCode = hashCode * 59 + this.Parameters.GetHashCode();
                return hashCode;
            }
        }
    }
}
