/* 
 * The OGC API - Processes
 *
 * WARNING - THIS IS WORK IN PROGRESS
 *
 * OpenAPI spec version: 1.0-draft.5
 * Contact: b.pross@52north.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineValue
    /// </summary>
    [DataContract]
    public partial class InlineValue : IEquatable<InlineValue>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineValue" /> class.
        /// </summary>
        /// <param name="inlineValue">inlineValue (required).</param>
        public InlineValue(string inlineValue = null)
        {
            // to ensure "inlineValue" is required (not null)
            if (inlineValue == null)
            {
                throw new InvalidDataException("inlineValue is a required property for InlineValue and cannot be null");
            }
            else
            {
                this._InlineValue = inlineValue;
            }
        }

        /// <summary>
        /// Gets or Sets _InlineValue
        /// </summary>
        [DataMember(Name = "inlineValue", EmitDefaultValue = false)]
        public string _InlineValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineValue {\n");
            sb.Append("  _InlineValue: ").Append(_InlineValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineValue);
        }

        /// <summary>
        /// Returns true if InlineValue instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineValue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineValue input)
        {
            if (input == null)
                return false;

            return
                (
                    this._InlineValue == input._InlineValue ||
                    (this._InlineValue != null &&
                    this._InlineValue.Equals(input._InlineValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._InlineValue != null)
                    hashCode = hashCode * 59 + this._InlineValue.GetHashCode();
                return hashCode;
            }
        }
    }
}
