/* 
 * The OGC API - Processes
 *
 * WARNING - THIS IS WORK IN PROGRESS
 *
 * OpenAPI spec version: 1.0-draft.5
 * Contact: b.pross@52north.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Input
    /// </summary>
    [DataContract]
        public partial class Input :  IEquatable<Input>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Input" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="input">input (required).</param>
        public Input(string id = default(string), IOneOfInput input = default(IOneOfInput))
        {
            // to ensure "id" is required (not null)
            //if (id == null)
            //{
            //    throw new InvalidDataException("id is a required property for Input and cannot be null");
            //}
            //else
            //{
            //    this.Id = id;
            //}
            //// to ensure "input" is required (not null)
            //if (input == null)
            //{
            //    throw new InvalidDataException("input is a required property for Input and cannot be null");
            //}
            //else
            //{
            //    this._Input = input;
            //}
            this.Id = id;
            this._Input = input;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets _Input
        /// </summary>
        [DataMember(Name="input", EmitDefaultValue=false)]
        public IOneOfInput _Input { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Input {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  _Input: ").Append(_Input).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Input);
        }

        /// <summary>
        /// Returns true if Input instances are equal
        /// </summary>
        /// <param name="input">Instance of Input to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Input input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this._Input == input._Input ||
                    (this._Input != null &&
                    this._Input.Equals(input._Input))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this._Input != null)
                    hashCode = hashCode * 59 + this._Input.GetHashCode();
                return hashCode;
            }
        }
    }
}
