/* 
 * The OGC API - Processes
 *
 * WARNING - THIS IS WORK IN PROGRESS
 *
 * OpenAPI spec version: 1.0-draft.5
 * Contact: b.pross@52north.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;

namespace IO.Swagger.Model
{
    public interface IOneOfInput
    {

        [DataMember(Name="value")]
        object Value { get; set; }
    }
}