/* 
 * The OGC API - Processes
 *
 * WARNING - THIS IS WORK IN PROGRESS
 *
 * OpenAPI spec version: 1.0-draft.5
 * Contact: b.pross@52north.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines jobControlOptions
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum JobControlOptions
    {
        /// <summary>
        /// Enum SyncExecute for value: sync-execute
        /// </summary>
        [EnumMember(Value = "sync-execute")]
        SyncExecute = 1,
        /// <summary>
        /// Enum AsyncExecute for value: async-execute
        /// </summary>
        [EnumMember(Value = "async-execute")]
        AsyncExecute = 2,

        /// <summary>
        /// Enum Dismiss for value: dismiss
        /// </summary>
        [EnumMember(Value = "dismiss")]
        Dismiss = 3
    }
}
