/* 
 * The OGC API - Processes
 *
 * WARNING - THIS IS WORK IN PROGRESS
 *
 * OpenAPI spec version: 1.0-draft.5
 * Contact: b.pross@52north.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines transmissionMode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransmissionMode
    {
        /// <summary>
        /// Enum Value for value: value
        /// </summary>
        [EnumMember(Value = "value")]
        Value = 1,
        /// <summary>
        /// Enum Reference for value: reference
        /// </summary>
        [EnumMember(Value = "reference")]
        Reference = 2
    }
}
